// actions for player
export const UPDATE_LYRIC = 'UPDATE_LYRIC';
export const UPDATE_LYRIC_PERCENT = 'UPDATE_LYRIC_PERCENT';
export const UPDATE_PLAYED_PERCENT = 'UPDATE_PLAYED_PERCENT';

// actions for song
export const START_FETCHING_SONG = 'START_FETCHING_SONG';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';
export const FETCH_SONG_FAILURE = 'FETCH_SONG_FAILURE';
export const FETCH_SUGGESTED_SONG_SUCCESS = 'FETCH_SUGGESTED_SONG_SUCCESS';
export const FETCH_SUGGESTED_SONG_FAILURE = 'FETCH_SUGGESTED_SONG_FAILURE';